screen:
  width: 1920
  height: 1080

regions:
  elixir_bar:
    x: 23
    y: 2395
    w: 1130
    h: 88

  timer:
    x: 900
    y: 20
    w: 120
    h: 60

  card_slot_1:
    x: 600
    y: 960
    w: 140
    h: 160

  card_slot_2:
    x: 760
    y: 960
    w: 140
    h: 160

  card_slot_3:
    x: 920
    y: 960
    w: 140
    h: 160

  card_slot_4:
    x: 1080
    y: 960
    w: 140
    h: 160

  board:
    x: 0
    y: 150
    w: 1920
    h: 700
