screen:
  x: 1071
  y: 123
  w: 505
  h: 899
elixir_bar:
  x: 132
  y: 865
  w: 256
  h: 22
timer:
  x: 430
  y: 22
  w: 61
  h: 23
card_slot_1:
  x: 113
  y: 743
  w: 90
  h: 115
card_slot_2:
  x: 207
  y: 743
  w: 90
  h: 115
card_slot_3:
  x: 303
  y: 743
  w: 90
  h: 115
card_slot_4:
  x: 397
  y: 743
  w: 90
  h: 115
next_card:
  x: 18
  y: 835
  w: 51
  h: 54
board:
  x: 0
  y: 3
  w: 504
  h: 722
