screen:
  width: 1920
  height: 1080

regions:
  elixir_bar:
    x: 23
    y: 2395
    w: 1130
    h: 88

  timer:
    x: 949
    y: 443
    w: 229
    h: 125

  card_slot_1:
    x: 150
    y: 2162
    w: 160
    h: 251

  card_slot_2:
    x: 305
    y: 2162
    w: 160
    h: 251

  card_slot_3:
    x: 460
    y: 2162
    w: 160
    h: 251

  card_slot_4:
    x: 615
    y: 2162
    w: 160
    h: 251

  next_card:
    x: 27
    y: 2229
    w: 92
    h: 116

  board:
    x: 60
    y: 660
    w: 1058
    h: 1476
